default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 12345
  timeout: 5000

development:
  <<: *default
  database: billinho_db_dev
  username: postgres
  password: 12345
  host: localhost
  port: 5432

test:
  <<: *default
  database: billinho_db_test
  username: postgres
  password: 12345
  host: localhost
  port: 5432

production:
  <<: *default
  database: billinho_db
  username: postgres
  password: 12345
  host: localhost
  port: 5432
